Force convert TX_POWER to string
When running wifite with specified TX power under Python 2.7, the script
would fail on the iwconfig call, supposedly because
self.RUN_CONFIG.TX_POWER is interpreted as an integer.
This commit tries to fix this issue by converting TX_POWER argument
to a string.
An example traceback with source lines left out (they are too wide to
fit in a 50/72 commit message) is below:

Traceback (most recent call last):
  File "/usr/local/bin/wifite", line 3525, in <module>
  File "/usr/local/bin/wifite", line 1383, in Start
  File "/usr/local/bin/wifite", line 1032, in get_iface
  File "/usr/local/bin/wifite", line 898, in enable_monitor_mode
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
  File "/usr/lib/python2.7/subprocess.py", line 1340, in _execute_child
TypeError: execv() arg 2 must contain only strings